### ISSUE TITLE
Produção do Documento de Especificação de Requisitos de Software

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#17]
## Progresso

- [x] Casos de uso #16 
- [x] Diagrama de componentes #19 
- [x] Diagrama Entidade-Relacionamento #20 
- [x] Diagrama de casos de uso #18 
- [ ] Documento completo ERSw
  - https://docs.google.com/document/d/1VYph8mOv1QY-TDfwUNr2TpXRU-wv-DX1lG9DDSQOva0

**Comment by CassianoJunior** [comment]
Vamos revisar o documento pessoal. Leiam e vejam se precisa de alguma coisa, se tem erro ou sugerir alguma modificação.

Mas leiam de verdade, não é só dar like nessa mensagem não.

@EduardoRibeiroBR @Amarildo-Jr @assis23

**Comment by EduardoRibeiroBR** [comment]
Ok

**Comment by assis23** [comment]
Declaro ok, também!
