### ISSUE TITLE
Produção dos tutoriais

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#3]
# Tutoriais:
- [x] T1 - Tutorial de como instalar e configurar linguagem e framework(s) escolhido(s) junto a IDE escolhida#4 
  - [x] Entrega 1 - #4 
  - [x] Entrega 2 - #21 
- [x] T2 - Tutorial de como criar uma aplicação web básica mostrando um formulário html, por exemplo: exibir um formulário de cadastro de usuário (usuário, nome completo, email, senha). #2 
  - Obs: procure detalhar os passos e os comandos necessários para executar a aplicação web e porta de execução.
- [x] T3 - Tutorial de como instalar e configurar o banco de dados escolhido. #5 
- [x] T4 - Tutorial de como persistir e recuperar dados de um usuário no Banco de Dados escolhido integrado a aplicação web (servidor). 
  - [x] Entrega 1 - #6 
  - [x] Entrega 2 - #10 
  - Por exemplo: pode-se criar um formulário de cadastro de usuário e um formulário para listar todos os usuários cadastrados no banco via aplicação web.
- [x] T5 - Tutorial de como fazer upload de arquivos para a aplicação web (servidor). Por exemplo: pode-se criar um formulário de upload de imagem e um formulário para listar os arquivos salvos na aplicação web. #7 
- [x] Tutorial de validação de entrada de dados do usuário em formulários diversos usando [React Hook Form](https://react-hook-form.com/) #8

**Comment by CassianoJunior** [comment]
[Link para o artefato](https://drive.google.com/file/d/19Df8bQxIeK5JJ9XopGekSeh7QWWcGGm-/view?usp=sharing)
