### ISSUE TITLE
Design e implementação do registro e login do usuário

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#33]
# Implementação do sistema de autenticação

- [x] Tela de Login - #34 
- [x] Tela de Registro de usuários - #35
- [x] Modelo de usuário no Prisma - #38 
- [x] Endpoint de Cadastro - #36 
- [x] Endpoint de Login - #37 
- [x] Middleware na API - #39 
- [x] Integrar com Next Auth - #40
