### ISSUE TITLE
Upload de imagens

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#42]
# Módulo de upload de imagens

- [ ] Componente de upload de imagens - #45 
- [x] Endpoint de upload - #44 
- [x] Integração com Dropbox - #43
